language: python

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "3.1"
  - "3.0"

install:
  - pip3 install -r requirements.txt
  - pip3 install codecov

script:
  - coverage run cronparser_test.py

after_success:
  - codecov